### ISSUE TITLE
Crash on opening Composition

### ISSUE THREAD

**Issue by danieldormann** [benkuper/Spout-AfterEffects#1]
Hey there,

I'm so far a big fan of your project and on my laptop it runs flawlessly. Funny enough I have the nearly same setup (software wise) on my Desktop PC, but here it crashes. I get following Visual C++ Debug Error:

> Debug Assertion Failed!
> 
> Program: ...Files\Adobe\Adobe After Effects CS6\Support Files\AfterFX.exe
> File: f:\dd\vctools\crt_bld\self_64_amd64\crt\src\tcscpy_s.inl
> Line: 30
> 
> Expression: (L "Buffer is too small" && 0)

and shortly after another Error from After Effects itself:

> After Effects error: Crash in progress.Last logged message was: <2012> <ae.blitpipe> <2> Making new Context

I'm running CS6 64bit on Windows 7. Spout V2.001-beta and VC++11.0 Redist. is installed. Which are the exact same versions on my laptop. I now it's hard to debug, when the debugger states it can't assert, but maybe you have an idea or hint. Would love to use it on my desktop too.

All the best,
Daniel Dormann

**Comment by benkuper** [comment]
I have sometimes this bug too, i suspect it comes from a wrong comp initialization. You may want to create an empty comp before opening an existing comp.

**Comment by lilkosi** [comment]
hey. Thanks for the application but i have the same Problem - AE always crashes when i create a new comp. Iam working on Windows 10 with AE CC

**Comment by 7dex** [comment]
Hey, no problems or crashes here, just needed to add the aex plugin file, not the others (follow the manual). Very comfortable :) Win 8.1 ae cs6-------- Originalnachricht --------Betreff: Re: [benkuper/Spout-AfterEffects] Crash on opening Composition (#1)Von: lilkosi An: benkuper/Spout-AfterEffects Cc: hey. Thanks for the application but i have the same Problem - AE always crashes when i create a new comp. Iam working on Windows 10 with AE CC

**Comment by dev-joss** [comment]
Having this issue in After Effects CC 2015. Crash also occurs when opening a project with and existing blank composition.
