### ISSUE TITLE
Crash in Unity

### ISSUE THREAD

**Issue by phieday** [benkuper/Spout-AfterEffects#2]
I'm having a problem with the plugin in unity. The demo scene works fine, you can start it and stop it within the editor but I can't seem to get it to work in a new scene. I set it up in the same way and start the player and when I stop it it crash Unity. I can send an example of the scene that crashes if that would help. Is there anything that needs to be set for this to not happen. 
The other thing I've noticed is that if I build the scene and run it it will crash when I quit.

The plugin will be really useful if I can get it to work like the demo scene. I create a player for the Oculus. http://whirligig.xyz/ and a why to stream after effects into a Unity texture would be very useful for film production.

Hope you can help, all the best.

Phil

**Comment by benkuper** [comment]
Hello,
AfterEffects changes it's comp size randomly, causing the texture to change its size.
This behavor is not a problem in most of the Spout-enabled apps, so it may come from the Unity plugin not handling well the texture size change.
Unity Spout plugin has changed its repo and is now called Spout4Unity, maintained by sloopidoopi. Latest version of this plugin may fix you problem
