### ISSUE TITLE
Does not work on AE 2015.3

### ISSUE THREAD

**Issue by pymenvert** [benkuper/Spout-AfterEffects#3]
Hello

Spout-AE does not work on my computer.
I placed the *.aex on plugin folder and the 2 *.dll on the After Effect folder.
When i launch AE, the spout receiver see the "AfterFX" Sender but there is no image.

The Sender and Receiver work properly with other application

System :
Windows 10 with Nvidia 970M 
After Effect 2015.3 (v.13.8.0.144)
Resolume 5.0.4 

Thanks a lot

**Comment by benkuper** [comment]
Hello, sorry i just saw this issue.
I will try on more recent version of AfterFX and update the plugin in the next days.

**Comment by benkuper** [comment]
Hello,
i finally got time to get my hands on it.
i tested with AE 2017 and i get the same problem. I'll try to resolve that today or tomorrow.

**Comment by benkuper** [comment]
Hi,
i update the code to work with AE2017, please tell me if it works for 2015.3 as well.
You can download it in the "releases" section or here :
https://github.com/benkuper/Spout-AfterEffects/releases/tag/CC2017

**Comment by pymenvert** [comment]
Hello Ben. 

Thanks for your update. 
Actually, am working with AE2017 so i will test your update tomorrow. 

Thanks a lot. 

Best Regards
Pym

**Comment by benkuper** [comment]
@pymenvert how did it go ?
