### ISSUE TITLE
Size of After Effects composition and Spout DX11 Receiver don't match.

### ISSUE THREAD

**Issue by xxJulexx** [benkuper/Spout-AfterEffects#4]
Hello

Size of After Effects composition and Spout DX11 Receiver don't match.
It must be "Width -4pix, Height +4pix" to match both size.
Spout-UE 4 and others have adverse effects.

These are reference screenshots.
https://gyazo.com/5532bf6580f399945a0ea0e55f022004
https://gyazo.com/008ec00574f2a97def396a8e5677e093

Windows 10 64bit
After Effect CC2014-CC2017
UnrealEngine 4.14

**Comment by rs3dtouch** [comment]
There is an related bug regarding Composition and Layer View in After Effects CS 6. 

In Composition View the wrong size (1924x1076) does not skew the image, but in Layer View the image gets distorted. Would be nice if you could the right value sets both Views!

(https://cloud.githubusercontent.com/assets/26660206/24311843/341d125e-10d6-11e7-89a8-65dd16d5ace4.jpg)

**Comment by benkuper** [comment]
Hello,
thanks to Phillip from Frischluft, this issue has been fixed.
I also updated the plugin so there is no more dependency to SpoutLibrary.dll anymore, the .aex file is the only file needed now.

Check it out on the release page : https://github.com/benkuper/Spout-AfterEffects/releases/tag/CC2017

Please confirm that this update fixes your problem, thanks !

**Comment by rs3dtouch** [comment]
Philipp is a friend of mine and was so nice to fix it :-) 

Works fine now in CS 5.5. and CS 6 now. Great that you put it up on Github so quickly!

**Comment by xxJulexx** [comment]
Works fine in CC2014 / CC2015.3 / CC2017.
Thunks!
