### ISSUE TITLE
Plug in CC2019

### ISSUE THREAD

**Issue by rlalire** [benkuper/Spout-AfterEffects#7]
Hi ! I downloaded the CC2017 plug in and sometimes my soft doesn't see the spout out ! I can't find the .AEX for after effects cc2019, does it exist ?

**Comment by benkuper** [comment]
Hello,
So sorry for the super late answer, I just realized that I had drafted the release but not hit the publish button, so it has always been there, just not public... and I completely missed your issue !
The plugin is online and should also work with CC2020
